site_title = "MyArxiv"
limit_days = 30
cache_url = "https://AlanLee234.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.DB"
title = "Databases"

[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.CE"
title = "Computational Engineering, Finance, and Science"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
